### ISSUE TITLE
Investigate `** (UndefinedFunctionError) function nil.temperature_c/0 is undefined`

### ISSUE THREAD

**Issue by mnishiguchi** [mnishiguchi/hello_nerves#1]
Error in webserver

```
 web.1  | 14:01:34.946 [error] an exception was raised:
 web.1  |     ** (UndefinedFunctionError) function nil.temperature_c/0 is undefined
 web.1  |         nil.temperature_c()
 web.1  |         (mnishiguchi 0.1.0) lib/mnishiguchi_web/live/environment_live.ex:83: anonymous fn/2 in MnishiguchiWeb.EnvironmentLive.render/1
 web.1  |         (phoenix_live_view 0.15.4) lib/phoenix_live_view/diff.ex:356: Phoenix.LiveView.Diff.traverse/6
 web.1  |         (phoenix_live_view 0.15.4) lib/phoenix_live_view/diff.ex:430: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
 web.1  |         (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
 web.1  |         (phoenix_live_view 0.15.4) lib/phoenix_live_view/diff.ex:356: Phoenix.LiveView.Diff.traverse/6
 web.1  |         (phoenix_live_view 0.15.4) lib/phoenix_live_view/diff.ex:430: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
 web.1  |         (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
```

**Comment by mnishiguchi** [comment]
Looks like gen server crashed due to shaky WIFI connection. Here is the log. 

```
14:04:45.050 [error] GenServer {VintageNet.Interface.Registry, {VintageNetWiFi.WPASupplicant, "wlan0"}} terminating
** (stop) exited in: GenServer.call(#PID<0.1484.0>, {:control_request, "BSS fc:51:a4:26:90:3a"}, 5000)
    ** (EXIT) time out
    (elixir 1.11.3) lib/gen_server.ex:1027: GenServer.call/3
    (vintage_net_wifi 0.9.2) lib/vintage_net_wifi/wpa_supplicant.ex:486: VintageNetWiFi.WPASupplicant.get_access_point_info/2
    (vintage_net_wifi 0.9.2) lib/vintage_net_wifi/wpa_supplicant.ex:212: VintageNetWiFi.WPASupplicant.handle_notification/2
    (vintage_net_wifi 0.9.2) lib/vintage_net_wifi/wpa_supplicant.ex:197: VintageNetWiFi.WPASupplicant.handle_info/2
    (stdlib 3.13.2) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13.2) gen_server.erl:756: :gen_server.handle_msg/6
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {VintageNetWiFi.WPASupplicantLL, 3, "CTRL-EVENT-BSS-ADDED 0 fc:51:a4:26:90:3a"}
State: %{access_points: %{}, ap_mode: false, clients: [], control_dir: "/tmp/vintage_net/wpa_supplicant", current_ap: nil, eap_status: %VintageNet.Interface.EAPStatus{method: nil, remote_certificate_verified?: false, status: nil, timestamp: nil}, ifname: "wlan0", keep_alive_interval: 60000, ll: #PID<0.1484.0>, peers: [], verbose: false, wpa_supplicant: "wpa_supplicant", wpa_supplicant_conf_path: "/tmp/vintage_net/wpa_supplicant.conf.wlan0"}
```

Probably we want to handle this type error in the web server so that it won't crash, just showing a warning message.
